"""empty message

Revision ID: d6f7c577b158
Revises: 
Create Date: 2019-03-12 22:32:11.861784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f7c577b158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btcprices',
    sa.Column('btcprice_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('base', sa.String(length=25), nullable=False),
    sa.Column('currency', sa.String(length=25), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sell', sa.Float(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('cmc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('btcprice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btcprices')
    # ### end Alembic commands ###
